### PR TITLE
Add send receipt and send fulfillment receipt flags to Order model

### PR DESCRIPTION
**Pull request by ggrant005**
* add `send_receipt` and `send_fulfillment_receipt` flags to `Order` model

These two flags are mentioned in the [REST API Docs](https://shopify.dev/api/admin-rest/2022-07/resources/order#post-orders), but were left out of the go API

### CODE REVIEW

**Comment by oliver006** [comment]
Thanks for your PR!
I recently joined as a maintainer and so PRs should move a bit quicker again.

Can you please rebase your PR so I can go ahead and merge it? Thanks!

**Comment by ggrant005** [comment]
> Thanks for your PR! I recently joined as a maintainer and so PRs should move a bit quicker again.
> 
> Can you please rebase your PR so I can go ahead and merge it? Thanks!

Done. Thanks!

**Review by oliver006 — APPROVED** [review]

**Comment by oliver006** [comment]
Can you resolve the merge conflicts please? Thanks!

**Comment by oliver006** [comment]
Fixed in #201

**Pull request closed without merging**
