### PR TITLE
adding go mod

### PR DESCRIPTION
**Pull request by luthermonson**
Moved to go modules by updating httpmock.v1 imports to httpmock and vendor locked at v1.0.4. checked in vendor directory, i personally like ./vendor checked in but if that's not what you like just tell me and I'll drop it.

### CODE REVIEW

**Comment by gordcurrie** [comment]
We haven't overlooked this one, we are still debating the pro's verses cons of vendoring in deps in libraries internally. I'm a fan of it for your regular codebase, trying to figure out if there are any drawbacks to doing it for libraries.

**Comment by luthermonson** [comment]
> We haven't overlooked this one, we are still debating the pro's verses cons of vendoring in deps in libraries internally. I'm a fan of it for your regular codebase, trying to figure out if there are any drawbacks to doing it for libraries.

no drawbacks that i know of, go mod grabs only what it needs. you may need to update some of your testing stuff to use -mod vendor to use the checked in libraries. it's personal preference though so if you choose not to it's fine and i kept it in it's own commit on purpose so i could drop it if you didn't like it. just let me know.

**Comment by luthermonson** [comment]
looks like all the `go test` stuff should be fine. I `cherry-pick`ed in the the theme CRUD stuff which included the go1.11-13 in the travis.yml so we can make sure everything runs in actual versions that had go modules.

**Comment by luthermonson** [comment]
yup we're good: https://travis-ci.org/bold-commerce/go-shopify/jobs/643768721?utm_medium=notification&utm_source=github_status

looks like with GO111MODULE=auto everyone is still happy.

**Comment by luthermonson** [comment]
@gordcurrie really need your decision on this, switching back/forth from go mod to get my other PRs is obnoxious. If you dont want vendors in git it's totally fine, just tell me.

**Comment by rickywiens** [comment]
Many popular go libraries do not check in their vendored files including [the github API library](https://github.com/google/go-github). A random sampling through [this list](https://github.com/avelino/awesome-go) and I could only find one other project that had checked in its vendor directory.

Based on the above, I think I would personally prefer it if we did not check in the vendor directory.

**Comment by luthermonson** [comment]
@rickywiens no problemo, removing that commit and repushing.

**Comment by luthermonson** [comment]
@gordcurrie @rickywiens all fixed thanks for the feedback

**Pull request merged**
