### PR TITLE
Code update for `2024-01`

### PR DESCRIPTION
**Pull request by deepsidhu1313**
* Added Currency and UpdatedAt properties in UsageCharge
* Removed Deprecated fields `accepts_marketing` and `accepts_marketing_updated_at` from customer object
* Exporting OrderFinancialStatus and OrderFulfillmentStatus from Order

### CODE REVIEW

**Review by sabelard-bold — APPROVED** [review]

**Review by AntonKosov — APPROVED** [review]

**Review by BoldBrandonM — DISMISSED** [review]

**Review by kkotowich — APPROVED** [review]

**Comment by oliver006** [comment]
Hey there! What's up with all the pre-releases @deepsidhu1313 ? 

PS: nice seeing some bold-commerce faces, what's up guys? It's been a while!

**Comment by deepsidhu1313** [comment]
> Hey there! What's up with all the pre-releases @deepsidhu1313 ?
> 
> PS: nice seeing some bold-commerce faces, what's up guys? It's been a while!

Hi, we are updating this library for one of our service, and we are using pre-releases to do some testing on local and staging instead of making final release on this repo.

**Comment by oliver006** [comment]
@deepsidhu1313 - want to get this RFR so we can get it merged?

**Review by ahmedkidwai — APPROVED** [review]

**Comment by deepsidhu1313** [comment]
@oliver006 code is ready for release. 
* Team has tested changes on staging
* Changes have been made to fix the issue that was found.

**Review by oliver006 — APPROVED** [review]
🎉

**Comment by oliver006** [comment]
Released as https://github.com/bold-commerce/go-shopify/releases/tag/v4.6.0

**Pull request merged**
