### PR TITLE
Add Order.CurrentTotalPrice.

### PR DESCRIPTION
**Pull request by ascherkus**

### CODE REVIEW

**Review by oliver006 — COMMENTED** [review]
🚀

**Comment by oliver006** [comment]
Thanks for your PR!
I recently joined as a maintainer and so things should move a bit quicker again.

**Review by oliver006 — APPROVED** [review]
🚀

**Comment by ascherkus** [comment]
Thanks! What are the next steps -- the checks seem to be stuck and not sure if I merge or if you merge. In any case thanks for the review!

**Comment by oliver006** [comment]
Yeah, the CI system is stuck. I'm working with the folks from Bold to get that sorted, sorry about that, I hope to have this working soon.

**Pull request merged**
