### PR TITLE
Add ListAll methods to resources with ListWithPagination methods

### PR DESCRIPTION
**Pull request by weirdian2k3**
This relates to https://github.com/bold-commerce/go-shopify/issues/230 

It looks like the `List` method only returns the first page for all of the resources that we have a `ListWithPagination`.

I wasn't super comfortable breaking backwards compatibility, so with this PR I'm adding a `ListAll` method that utilizes `ListWithPagination` to pull all of the items

### CODE REVIEW

**Comment by oliver006** [comment]
Thanks for the PR!
I'm a bit slammed right now but will try to get to it in the next few days. Please ping me if you don't hear back from me.

**Comment by weirdian2k3** [comment]
@oliver006 no worries. This is this week's ping. I'll hit you up again in a week if I don't hear from you

**Comment by oliver006** [comment]
Just catching up here and with #230 so bear with me if I'm a bit slow.

> I wasn't super comfortable breaking backwards compatibility

re: backwards compatibility: is your concern that people currently expect `List()` to return only the first page (or at least not a ton of data) and changing that could cause breakage? 

I think that makes sense though I wish we could go back and make the change that List() returns all data (like your ListAll() call) and ListWithPagination could be used for more selective access.

v4.0 is kinda new - do you think we could still make that kind of change and release it as 4.1 ?

**Comment by weirdian2k3** [comment]
> Just catching up here and with #230 so bear with me if I'm a bit slow.
> 
> > I wasn't super comfortable breaking backwards compatibility
> 
> re: backwards compatibility: is your concern that people currently expect `List()` to return only the first page (or at least not a ton of data) and changing that could cause breakage?

Exactly, I don't want to be the reason someone was downloading 50 items and is now downloading 5,000 just by updating a dependency

> v4.0 is kinda new - do you think we could still make that kind of change and release it as 4.1 ?

We can, but I'm worried that could be confusing since the pagination was only added to some of the endpoints, so `List` might still return just some for the other entities

I think the easiest option is to go with this for now, then go through and see what other entities now support pagination (if there have been any additions) and if there is now pagination for all endpoints, introduce that as a breaking change in maybe a 4.2

**Comment by oliver006** [comment]
I think what you say makes sense, let's keep ListAll()

**Review by oliver006 — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
