### PR TITLE
Fix some linting warnings (plus future use of staticcheck?)

### PR DESCRIPTION
**Pull request by c9845**
- Comment out unused code.
- Fix incorrect JSON struct tag (missing opening double-quote).
- Remove unneeded type inside slice of type ("redundant type from array, slice, or map composite literal" warning).

---

There are a lot of other warnings shown by `staticcheck` that were not fixed (`staticcheck` isn't in use for this repo).  Most of these warnings are for the checks listed below.  Fixing these is a rather big change, just due to volume of lines changed.   **Whether or not we want to implement `staticcheck` is the question.**

- ST1003 (using Api instead of API in struct field name).
- ST1021 (not starting the documentation of an exported type with it's name.
- ST1020 (not starting the documentation of an exported method or func with the method's name).

Changing field names per warning ST1003 is a breaking change, so is probably best to be avoided (staticcheck.conf would be set to `checks="all", "-ST1003"]`).  Fixes for the other warnings are no issue since these are just a documentation change.

Examples to be fixed...

- abandoned_checkout.go:25:1: comment on exported type AbandonedCheckoutsResource should be of the form "AbandonedCheckoutsResource ..." (with optional leading article) (ST1021) 
- abandoned_checkout.go:85:1: comment on exported method List should be of the form "List ..." (ST1020) 
- blog.go:49:1: comment on exported type BlogResource should be of the form "BlogResource ..." (with optional leading article) (ST1021) 
- carrier.go:75:1: comment on exported type ShippingRateAddress should be of the form "ShippingRateAddress ..." (with optional leading article) (ST1021) 
- carrier.go: 100:1: comment on exported type ShippingRateResponse should be of the form "ShippingRateResponse ..." (with optional leading article) (ST1021) 
- collect.go:39:1: comment on exported type CollectResource should be of the form "CollectResource ..." (with optional leading article) (ST1021) 
- collect.go:44:1: comment on exported type CollectsResource should be of the form "CollectsResource ..." (with optional leading article) (ST1021) 
- collection.go:39:1: comment on exported type CollectionResource should be of the form "CollectionResource ..." (with optional leading article) (ST1021) 
- collection.go:52:1: comment on exported method ListProducts should be of the form "ListProducts ..." (ST1020)

### CODE REVIEW

**Comment by oliver006** [comment]
Thanks for opening this PR - it still seems to be WIP - ping me when you're ready for review or feedback.

**Comment by c9845** [comment]
@oliver006 I am done with this for now.  

The questions becomes, do we want to implement `staticcheck` for the repo.  If yes, then this becomes a much larger change.

**Comment by oliver006** [comment]
Thanks for clarifying.
Leaving commented out code in the repo is not a good practice, dead code should just be removed unless there's a very good reason.
The rest of the changes look alright.
If you could clean up the commented-out code stuff then I think we should e good to go.

**Comment by c9845** [comment]
@oliver006 Commented out code has been removed.

What are your thoughts on utilizing `staticcheck`?

**Comment by oliver006** [comment]
Thanks @c9845  - this should be good to go.
I don't think there's an urgent need for adding `staticcheck` to the CI right now. If you submit a PR then I'll review it but I don't have the time right now to add it myself.

**Review by oliver006 — APPROVED** [review]
👍

**Pull request merged**
