### PR TITLE
add product status

### PR DESCRIPTION
**Pull request by s-norris**
Added the Status field to the product struct
Docs here: https://shopify.dev/docs/admin-api/rest/reference/products/product

This has been tested against v2021-01 and v2021-04

### CODE REVIEW

**Review by justinkoke — DISMISSED** [review]
Thanks Simon, this is fantastic ... we ran into the same problem with the library just today.

**Comment by catalogplus** [comment]
Hi, is someone planning to merge this?

**Comment by ckeyes88** [comment]
Any update on this? Would be nice to be able to make use of product status

**Comment by oliver006** [comment]
Fixed by #190

**Pull request closed without merging**
